# Generated by Django 5.1.1 on 2024-09-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_moodentry_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='mood_intensity',
        ),
    ]
